title: Kode2Learn | Miami University

# Social Media
twitter_link: https://twitter.com/Kode2Learn
facebook_link: https://www.facebook.com/Kode2Learn/
github_link: https://github.com/kode2learn

primary_contact: 'Nora Husani <husaninm@miamioh.edu>'
secondary_contacts: 'Matt DePero <deperomm@miamioh.edu>, Molly McConaughey <mcconamb@miamioh.edu>'