title: Kode2Learn | Miami University

# Social Media
twitter_link: https://twitter.com/Kode2Learn
facebook_link: https://www.facebook.com/Kode2Learn/
github_link: https://github.com/kode2learn

primary_contact: 'Nora Husani <husaninm@miamioh.edu>'

# Contact Form
## ******* NOTE: any email address included on the contact form needs to validate their email. Just change the values below, push the changes to the website, and then submit something to the form. The first time your email address is used it will ask you to validate it.
contact_form_email: 'deperomm@miamioh.edu';
secondary_contacts: 'Matt DePero <deperomm@miamioh.edu>, Molly McConaughey <mcconamb@miamioh.edu>, Nora Husani <husaninm@miamioh.edu>'